### PR TITLE
[issue37] add navbar

### LINKED ISSUE #37: create the navbar(v2)
**Is your feature request related to a problem? Please describe.**

**Describe how the solution should behave**

**Screenshots of the design/if any**
Clear screenshots of the design for this feature.

**Additional context**

### PR DESCRIPTION
**Pull request by RawandDev**
## What?
I made the navbar.
## Why?
Because navbar is an important part of the web.
## How to use?
You can use navbar to switch between routes and navigate through them.
## Screenshots 
A clear screenshots of your work.
## Gif
Desktop:
https://gyazo.com/6dd432a0902927556093d35baaf3fbac

Mobile:
https://gyazo.com/38a7c60916819d11cf9a0230dc20452f

### CODE REVIEW

**Comment by RawandDev** [comment]
@MuhannedNoman Can you please review this.

**Comment by MuhannedNoman** [comment]
Can we fix this alignment, also add some padding to the top of the navbar looks squeezed to the top too much.
image

**Comment by RawandDev** [comment]
> Can we fix this alignment, also add some padding to the top of the navbar looks squeezed to the top too much.
> image

Sure, I will do it

**Review by Niyaz-Dev12 — COMMENTED** [review]
good job rawand
Screenshot 2021-10-16 162332
*can you align the burger menu better so that it's more to the right also make it bigger 
* one other thing is can you make it three lines the menu is just two lines it's not a burger. 
*there should be more padding the logo and the burger look so squeezed to the top.
* when you open the menu the background is white it doesn't go well with the body color 
aa
also here can you add a blue hover effect so that they know which one they're selecting

**Comment by RawandDev** [comment]
> Can we fix this alignment, also add some padding to the top of the navbar looks squeezed to the top too much. image

Done.

**Comment by RawandDev** [comment]
> good job rawand Screenshot 2021-10-16 162332 *can you align the burger menu better so that it's more to the right also make it bigger
> 
> * one other thing is can you make it three lines the menu is just two lines it's not a burger.
>   *there should be more padding the logo and the burger look so squeezed to the top.
> * when you open the menu the background is white it doesn't go well with the body color
>   aa
>   also here can you add a blue hover effect so that they know which one they're selecting

I forgot to add three lines menu but I will do it. For the second suggestion, I don't know what colour it should be. I added the hover effect.

**Comment by RawandDev** [comment]
@MuhannedNoman Can you please check this PR?

**Review by MuhannedNoman — APPROVED** [review]
LGTM, feel free to merge.

**Pull request merged**
