### PR TITLE
component(error): style error page

### LINKED ISSUE #7: Create the 404 page.
**Is your feature request related to a problem? Please describe.**

**Describe how the solution should behave**
The design should be exactly the same and responsive to the three screen sizes, desktop, tablet, and phone.

**Screenshots of the design/if any**
image

**Additional context**

### PR DESCRIPTION
**Pull request by RawandDev**

### CODE REVIEW

**Comment by RawandDev** [comment]
Please don't accept this until we are done with routing.

**Review by AhmedAlrahoo — DISMISSED** [review]

**Comment by RawandDev** [comment]
@MuhannedNoman @AhmedAlrahoo Please review if you have time.

**Review by MuhannedNoman — APPROVED** [review]
LGTML, but can you link the router to show this! I couldn't see it in the deployment.

**Comment by RawandDev** [comment]
> LGTML, but can you link the router to show this! I couldn't see it in the deployment.

I only linked to route="/error". Now it is linked to routes that are not found.

**Pull request merged**
