### PR TITLE
[ issue19 ] Create Book Page

### PR DESCRIPTION
**Pull request by Niyaz-Dev12**

### CODE REVIEW

**Comment by RawandDev** [comment]
I think you also need to add muhanned as a reviewr.

**Comment by Niyaz-Dev12** [comment]
I think He said to just mention him at the end you're the leader now

**Comment by RawandDev** [comment]
> I think He said to just mention him at the end you're the leader now

Ok, please let me know when you are finished.

**Comment by Niyaz-Dev12** [comment]
> > I think He said to just mention him at the end you're the leader now
> 
> Ok, please let me know when you are finished.

@RawandDev it's finished if you could take a look

**Review by MuhannedNoman — APPROVED** [review]
LGTM.

**Pull request closed without merging**
