### PR TITLE
create favorite page

### LINKED ISSUE #41: Create Favorites Page
**Is your feature request related to a problem? Please describe.**
N/A

**Describe how the solution should behave**
This page will allow the user to look through his bookmarked books. It has a heading, and Pagination. You should be able to render CardCompnents as displayed in the images.

**Screenshots of the design/if any**
Screenshot 2021-10-16 171301

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Niyaz-Dev12**

### CODE REVIEW

**Review by RawandDev — COMMENTED** [review]
Well done niyaz.
I think it would be better to fill out the heart since it is in favourites.
There is also an issue with the BookCard component but not sure if we can fix it here or needs a new PR.

https://gyazo.com/16f0597117a7232f50305c56d542e5f8

**Comment by Niyaz-Dev12** [comment]
> Well done niyaz. I think it would be better to fill out the heart since it is in favourites. There is also an issue with the BookCard component but not sure if we can fix it here or needs a new PR.
> 
> https://gyazo.com/16f0597117a7232f50305c56d542e5f8

1) about the heart it's gonna be a boolean value coming from the firestore that's why i didn't implement it yet i will do that 
2) the bookcard i don't think it can be fixed with tailwind because it has fixed screen sizes unless we make a custom one. also it's just for a specific screen size as it gets a little larger it gets fixed bases on the   

> Well done niyaz. I think it would be better to fill out the heart since it is in favourites. There is also an issue with the BookCard component but not sure if we can fix it here or needs a new PR.
> 
> https://gyazo.com/16f0597117a7232f50305c56d542e5f8

1) about the heart icon since we're getting boolean data from firestore i left it like this for now but i will do it no worries
2) but the BookCard i don't think there's a solution unless we add a custom responsive screen to that particular screen. i can decrease the width but it will not look nice on bigger screens

**Comment by Niyaz-Dev12** [comment]
i Added the Toggle to the heart icon you can click to bookmark so when the data comes from firestore if it's true it will be filled if false it will not be filled the reason why it's not filled because i set the isFavorite boolean state manually

**Review by RawandDev — APPROVED** [review]
Nice work Niyaz. This LGTM.
@MuhannedNoman

**Review by MuhannedNoman — APPROVED** [review]
LGTM. Feel free to merge.

**Pull request merged**
